package com.uitnetwork.botadmin.model

import com.amazonaws.services.dynamodbv2.datamodeling.*
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType.S

@DynamoDBTable(tableName = "CloudBotPermission")
data class CloudBotPermission(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,

        @DynamoDBTyped(S)
        @DynamoDBAttribute
        var userId: String,

        @DynamoDBAttribute
        var source: String,

        @DynamoDBAttribute
        var permissions: List<String>
)


